local druid = require("druid.druid")
local properties_panel = require("widget.Insality.properties_panel.properties_panel")
local debug_page_quest = require("widget.Insality.debug_page_quest.debug_page_quest")

local quest = require("quest.quest")

local function init_quest(self)
	quest.init({
		["intro"] = {
			autostart = true,
			autofinish = true,
			tasks = {{ action = "load_scene", object = "menu" }},
			category = "game",
		},
		["tutorial_quest"] = {
			required_quests = "intro",
			autostart = true,
			tasks = {{ action = "click", object = "play" }},
			category = "game",
		},
		["tutorial_quest_2"] = {
			required_quests = "tutorial_quest",
			autostart = true,
			tasks = {{ action = "click", object = "money", required = 50 }},
			category = "game",
		},
	})
end

function init(self)
	self.druid = druid.new(self)

	init_quest(self)

	self.properties_panel = self.druid:new_widget(properties_panel, "properties_panel")
	self.properties_panel:set_header("Debug Panel")

	self.properties_panel:add_button(function(button)
		button:set_text_property("Quest")
		button:set_text_button("Open")
		button.button.on_click:subscribe(function()
			debug_page_quest.render_properties_panel(self.druid, self.properties_panel)
		end)
	end)
end

function final(self)
	self.druid:final()
end

function update(self, dt)
	self.druid:update(dt)
end

function on_message(self, message_id, message, sender)
	self.druid:on_message(message_id, message, sender)
end

function on_input(self, action_id, action)
	return self.druid:on_input(action_id, action)
end
