local druid = require("druid.druid")

function init(self)
    self.druid = druid.new(self)

	local group_textures = gui.get_node("group")
	gui.animate(group_textures, "position", vmath.vector3(500, 365, 0), gui.EASING_INOUTSINE, 2, 0, nil, gui.PLAYBACK_LOOP_FORWARD)
end

function final(self)
    self.druid:final()
end

function update(self, dt)
    self.druid:update(dt)
end

function on_message(self, message_id, message, sender)
    self.druid:on_message(message_id, message, sender)
end

function on_input(self, action_id, action)
    return self.druid:on_input(action_id, action)
end
