local druid = require("druid.druid")
local rich_input = require("widget.Insality.rich_input.rich_input")

function init(self)
	self.druid = druid.new(self)
	self.rich_input = self.druid:new_widget(rich_input, "rich_input")
	self.rich_input:set_placeholder("Enter text...")
	self.rich_input.input.on_input_unselect:subscribe(function(_, text)
		print("Input changed", text)
	end)
end

function final(self)
	self.druid:final()
end

function update(self, dt)
	self.druid:update(dt)
end

function on_message(self, message_id, message, sender)
	self.druid:on_message(message_id, message, sender)
end

function on_input(self, action_id, action)
	return self.druid:on_input(action_id, action)
end
