local druid = require("druid.druid")
local properties_panel = require("widget.Insality.properties_panel.properties_panel")
local debug_page_token = require("widget.Insality.debug_page_token.debug_page_token")

local token = require("token.token")


local function init_token(self)
	token.init({
		["gold"] = { default = 100},
		["level"] = { default = 1, min = 1, max = 100},
		["money"] = { default = 0 }
	})

	local wallet = token.container("wallet")
	wallet:add("money", 500)
	wallet:add("gold", 100)
	wallet:add("level", 5)

	local inventory = token.container("inventory")
	inventory:add("item_sword", 1)
	inventory:add("item_shield", 1)
	inventory:add("item_helmet", 1)
	inventory:add("item_boots", 1)
	inventory:add("item_pants", 1)
	inventory:add("item_shirt", 2)
	inventory:add("item_pants", 1)
end


function init(self)
	self.druid = druid.new(self)

	init_token(self)

	self.properties_panel = self.druid:new_widget(properties_panel, "properties_panel")
	self.properties_panel:set_header("Debug Panel")

	self.properties_panel:add_button(function(button)
		button:set_text_property("Token")
		button:set_text_button("Open")
		button.button.on_click:subscribe(function()
			debug_page_token.render_properties_panel(self.druid, self.properties_panel)
		end)
	end)
end

function final(self)
	self.druid:final()
end

function update(self, dt)
	self.druid:update(dt)
end

function on_message(self, message_id, message, sender)
	self.druid:on_message(message_id, message, sender)
end

function on_input(self, action_id, action)
	return self.druid:on_input(action_id, action)
end
