local druid = require("druid.druid")
local properties_panel = require("widget.Insality.properties_panel.properties_panel")
local debug_page_decore = require("widget.Insality.debug_page_decore.debug_page_decore")

local decore = require("decore.decore")

function init(self)
	self.druid = druid.new(self)
	self.world = decore.new_world(
		require("system.Insality.transform.transform_system").create(),
		require("system.Insality.game_object.game_object_system").create(),
		require("system.Insality.input.input_system").create()
	)

	self.properties_panel = self.druid:new_widget(properties_panel, "properties_panel")
	self.properties_panel:set_header("Debug Panel")

	self.properties_panel:add_button(function(button)
		button:set_text_property("Decore")
		button:set_text_button("Open")
		button.button.on_click:subscribe(function()
			if self.world then
				debug_page_decore.render_properties_panel(self.world, self.druid, self.properties_panel)
			end
		end)
	end)
end

function final(self)
	self.druid:final()
end

function update(self, dt)
	self.world:update(dt)
	self.druid:update(dt)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("set_world") then
		self.world = message.world
	end
	self.druid:on_message(message_id, message, sender)
end

function on_input(self, action_id, action)
	return self.druid:on_input(action_id, action)
end
